version: '3.8'
services:
  social_network_backend_auth_service_postgres_db:
    image: postgres:14.1-alpine
    container_name: social_network_backend_auth_service_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=social_network_backend_auth_service_postgres_db
    ports:
      - '5421:5432'
  social_network_backend_profile_service_postgres_db:
    image: postgres:14.1-alpine
    container_name: social_network_backend_profile_service_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=social_network_backend_profile_service_postgres_db
    ports:
      - '5422:5432'
  social_network_backend_content_service_postgres_db:
    image: postgres:14.1-alpine
    container_name: social_network_backend_content_service_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=social_network_backend_content_service_postgres_db
    ports:
      - '5423:5432'
  social_network_backend_notification_service_postgres_db:
    image: postgres:14.1-alpine
    container_name: social_network_backend_notification_service_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=social_network_backend_notification_service_postgres_db
    ports:
      - '5424:5432'
  social_network_backend_like_service_postgres_db:
    image: postgres:14.1-alpine
    container_name: social_network_backend_like_service_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=social_network_backend_like_service_postgres_db
    ports:
      - '5425:5432'
  social_network_backend_follower_service_postgres_db:
    image: postgres:14.1-alpine
    container_name: social_network_backend_follower_service_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=social_network_backend_follower_service_postgres_db
    ports:
      - '5426:5432'
  social_network_backend_direction_service_postgres_db:
    image: postgres:14.1-alpine
    container_name: social_network_backend_direction_service_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=social_network_backend_direction_service_postgres_db
    ports:
      - '5427:5432'
  social_network_backend_like_service_redis_db:
    image: redis:7.0.4-alpine3.16
    container_name: social_network_backend_like_service_redis_db
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'